2 login register
ppokorni/autoshare_api pull request #5
Opened 2022-04-08 16:20 UTC by ppokorni

2022-04-10 09:22 UTC, mario11596 approved these changes
Sve je dobro, jedino treba dodati 'surname' polje u Register

2022-04-10 11:02 UTC, Darijan23 requested changes
Uz polje name, dodati i surname u usera

2022-04-10 11:02 UTC, Darijan23 commented on database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php
> +            $table->string('name');
Možda bi bilo dobro imati odvojene stupce Name i Surname?

2022-04-10 11:02 UTC, Darijan23 commented on app/Http/Controllers/Api/AuthController.php
> +                'name' => 'nullable'
Također, da se pri registraciji primaju odvojena polja name i surname

2022-04-11 11:26 UTC, Darijan23 approved these changes

2022-04-11 11:27 UTC, merged